# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 061ee73c78d661a77389f6703b03cec50021c0d20fb34e29e417220a10cd23592bcac2155b4419f2b6bf17a36aa77a9f904d597e34fc4e805002f1b4e3787743
  jwt_secret: 12jda91kkamnc0012mmfj93fjm001mm126703b03cec50021c0d20fb34e29e417220a10cd23592bcac2155b4419f2b6bf17a36aa77a9f904d597e34fc4e805002f1b4e3787743
  jwt_expirations_hours: 200
  escrow:
    url: https://api.escrow-sandbox.com/2017-09-01/
    api_key: 740_j0EPs7Mi7IDD2fPBtdp05Sw4gVnhV8RNYiK1eHvJUC5bMgYjw8noNxLdedlkz0K4
    email: kamal@evolvemachinelearners.com

test:
  secret_key_base: c3118772bd4bc3e26e547e2fe740dc07cc6a3b294bbbc1791f648f7f71874fb362da2c7637c6ae00abe666dfeca6b46cb1a080e6e9a9be368b17661cb47738fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  escrow:
    url: https://api.escrow-sandbox.com/2017-09-01/
    api_key: 740_j0EPs7Mi7IDD2fPBtdp05Sw4gVnhV8RNYiK1eHvJUC5bMgYjw8noNxLdedlkz0K4
    email: kamal@evolvemachinelearners.com

